name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      # Pull repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm test